const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const video=$('#heroVideo'), enter=$('#enterLayer'), hero=$('.hero'), sound=$('#soundBtn');
$('#enterBtn').addEventListener('click',async()=>{enter.classList.add('hide');hero.classList.add('playing');video.muted=false;try{await video.play()}catch{video.muted=true;await video.play();sound.querySelector('span').textContent='OFF'}});
sound.addEventListener('click',()=>{video.muted=!video.muted;sound.querySelector('span').textContent=video.muted?'OFF':'ON'});
video.addEventListener('ended',()=>{hero.classList.add('playing')});
const menu=$('#menuPanel'); $('#menuBtn').onclick=()=>{menu.classList.add('open');menu.setAttribute('aria-hidden','false')}; $('#menuClose').onclick=closeMenu; $$('#menuPanel a').forEach(a=>a.onclick=closeMenu); function closeMenu(){menu.classList.remove('open');menu.setAttribute('aria-hidden','true')}
const search=$('#searchPanel'), input=$('#siteSearch'), results=$('#searchResults'); $('#searchBtn').onclick=()=>{search.classList.add('open');search.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),500)}; $('#searchClose').onclick=()=>{search.classList.remove('open');search.setAttribute('aria-hidden','true')};
input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();results.innerHTML='';if(!q)return;const found=$$('[data-search]').filter(x=>x.dataset.search.toLowerCase().includes(q)||x.textContent.toLowerCase().includes(q));results.innerHTML=found.length?found.map(x=>`<div class="search-result">${x.querySelector('h3').textContent}</div>`).join(''):'<div class="search-result">No results found.</div>'});
const copy={
en:{internationalOnline:'International / Online',founderRole:'Founder & Creative Director',founderName:'Zahra Khansari',internationalStudio:'International Studio',navServices:'Services',navWork:'Selected Work',navTools:'Free Tools',navJournal:'Journal',navShop:'Shop',navContact:'Contact',searchLabel:'Search the studio',enter:'Enter the Fourth Dimension',soundNotice:'Experience begins with sound',heroTitle:'Beyond the visible.',heroText:'Spaces, identities and digital experiences designed as one connected world.',explore:'Explore the studio ↓',manifesto:'We turn complex ideas into spaces, stories and intelligent products.',servicesTitle:'One studio. Multiple dimensions.',servicesIntro:'Choose a service to enter its world.',s1:'Architecture & BIM',s1p:'Concept, interior, exterior, Revit modeling and cinematic visualization.',s2:'AI & Content Creation',s2p:'AI-assisted images, campaigns, content systems and visual experiments.',s3:'Teasers & Motion',s3p:'Logo motion, teasers and scroll-stopping cinematic advertising.',s4:'Website & App Design',s4p:'Immersive multilingual websites and application experiences.',s5:'Automation & AI Agents',s5p:'Connected intelligent workflows that automate repetitive business tasks.',s6:'Articles & Books',s6p:'Expert articles, digital books, interactive stories and editorial design.',viewService:'View service ↗',workTitle:'Designed to move people.',toolsTitle:'Useful tools, free to use.',toolsText:'Small intelligent tools built for creators, architects and growing brands.',pdfTool:'Smart PDF Studio',promptTool:'Architecture Prompt Builder',briefTool:'Creative Brief Generator',coming:'Coming soon',journalTitle:'Curated insight—not content noise.',journalText:'Expert articles shaped from trusted sources, reviewed before publication and presented as immersive stories.',readJournal:'Enter the journal →',shopTitle:'Files, books and creative systems.',visitShop:'Visit shop ↗',contactTitle:'Have an idea worth building?',startProject:'Start a project ↗'},
fa:{internationalOnline:'بین‌المللی / آنلاین',founderRole:'بنیان‌گذار و مدیر خلاق',founderName:'زهرا خوانساری',internationalStudio:'استودیو بین‌المللی',navServices:'خدمات',navWork:'نمونه‌کارها',navTools:'ابزارهای رایگان',navJournal:'مجله',navShop:'فروشگاه',navContact:'ارتباط با ما',searchLabel:'جست‌وجو در استودیو',enter:'ورود به بُعد چهارم',soundNotice:'تجربه با صدا آغاز می‌شود',heroTitle:'فراتر از آنچه دیده می‌شود.',heroText:'فضا، هویت و تجربه‌های دیجیتال؛ طراحی‌شده به‌عنوان یک جهان یکپارچه.',explore:'مشاهده استودیو ↓',manifesto:'ایده‌های پیچیده را به فضا، داستان و محصولات هوشمند تبدیل می‌کنیم.',servicesTitle:'یک استودیو، چندین بُعد.',servicesIntro:'یک خدمت را انتخاب کنید و وارد دنیای آن شوید.',s1:'معماری و BIM',s1p:'کانسپت، طراحی داخلی و خارجی، مدل‌سازی رویت و رندر سینمایی.',s2:'استودیوی خلاق هوش مصنوعی',s2p:'تصاویر، کمپین‌ها، سیستم‌های محتوایی و تجربه‌های بصری مبتنی بر AI.',s3:'موشن و تبلیغات',s3p:'لوگوموشن، تیزر و تبلیغات سینمایی تأثیرگذار.',s4:'وب‌سایت، اپلیکیشن و اتوماسیون',s4p:'سایت‌های تعاملی، اپلیکیشن و گردش‌کارهای هوشمند متصل.',s5:'کتاب و محتوای تخصصی',s5p:'مقاله، کتاب دیجیتال، داستان تعاملی و طراحی محتوای حرفه‌ای.',viewService:'مشاهده خدمت ↗',workTitle:'طراحی برای تأثیرگذاری.',toolsTitle:'ابزارهای مفید و رایگان.',toolsText:'ابزارهای هوشمند برای طراحان، معماران و برندهای درحال رشد.',pdfTool:'استودیوی هوشمند PDF',promptTool:'سازنده پرامپت معماری',briefTool:'سازنده بریف خلاق',coming:'به‌زودی',journalTitle:'دانش انتخاب‌شده، نه محتوای بی‌هدف.',journalText:'مقاله‌های تخصصی بر پایه منابع معتبر، بررسی‌شده پیش از انتشار و ارائه‌شده به‌شکل تعاملی.',readJournal:'ورود به مجله ←',shopTitle:'فایل، کتاب و سیستم‌های خلاق.',visitShop:'ورود به فروشگاه ↗',contactTitle:'ایده‌ای داری که ارزش ساختن دارد؟',startProject:'شروع پروژه ↗'},
ar:{internationalOnline:'دولي / عبر الإنترنت',founderRole:'المؤسِّسة والمديرة الإبداعية',founderName:'زهرا خوانساري',internationalStudio:'استوديو دولي',navServices:'الخدمات',navWork:'أعمال مختارة',navTools:'أدوات مجانية',navJournal:'المجلة',navShop:'المتجر',navContact:'اتصل بنا',searchLabel:'ابحث في الاستوديو',enter:'ادخل إلى البُعد الرابع',soundNotice:'تبدأ التجربة مع الصوت',heroTitle:'أبعد مما تراه.',heroText:'مساحات وهويات وتجارب رقمية مصممة كعالم واحد مترابط.',explore:'اكتشف الاستوديو ↓',manifesto:'نحوّل الأفكار المعقدة إلى مساحات وقصص ومنتجات ذكية.',servicesTitle:'استوديو واحد، أبعاد متعددة.',servicesIntro:'اختر خدمة وادخل إلى عالمها.',s1:'العمارة وBIM',s1p:'تصميم معماري وداخلي وخارجي، نمذجة Revit وإظهار سينمائي.',s2:'استوديو الذكاء الاصطناعي',s2p:'صور وحملات وأنظمة محتوى وتجارب بصرية مدعومة بالذكاء الاصطناعي.',s3:'الموشن والإعلان',s3p:'تحريك الشعارات والإعلانات التشويقية والمحتوى السينمائي.',s4:'المواقع والتطبيقات والأتمتة',s4p:'مواقع تفاعلية وتطبيقات ومسارات عمل ذكية ومتصلة.',s5:'الكتب والمحتوى',s5p:'مقالات وكتب رقمية وقصص تفاعلية وتصميم تحريري.',viewService:'عرض الخدمة ↗',workTitle:'تصميم يحرّك الناس.',toolsTitle:'أدوات مفيدة ومجانية.',toolsText:'أدوات ذكية للمبدعين والمعماريين والعلامات الطموحة.',pdfTool:'استوديو PDF الذكي',promptTool:'منشئ برومبت العمارة',briefTool:'منشئ الملخص الإبداعي',coming:'قريباً',journalTitle:'معرفة منتقاة، لا ضوضاء محتوى.',journalText:'مقالات احترافية من مصادر موثوقة، تُراجع قبل النشر وتُقدم كتجارب غامرة.',readJournal:'ادخل المجلة ←',shopTitle:'ملفات وكتب وأنظمة إبداعية.',visitShop:'زيارة المتجر ↗',contactTitle:'لديك فكرة تستحق البناء؟',startProject:'ابدأ مشروعاً ↗'}};
Object.assign(copy.fa,{s2:'هوش مصنوعی و تولید محتوا',s3:'تیزر و موشن',s4:'طراحی سایت و اپلیکیشن',s4p:'طراحی تجربه‌های چندزبانه، تعاملی و حرفه‌ای برای وب‌سایت و اپلیکیشن.',s5:'اتوماسیون و ایجنت‌های هوشمند',s5p:'گردش‌کارهای متصل و هوشمند برای خودکارسازی کارهای تکراری کسب‌وکار.',s6:'مقاله و کتاب',s6p:'مقالات تخصصی، کتاب‌های دیجیتال، داستان‌های تعاملی و طراحی محتوای حرفه‌ای.'});
Object.assign(copy.ar,{s2:'الذكاء الاصطناعي وصناعة المحتوى',s3:'الإعلانات والموشن',s4:'تصميم المواقع والتطبيقات',s4p:'تجارب رقمية متعددة اللغات وتفاعلية للمواقع والتطبيقات.',s5:'الأتمتة والوكلاء الأذكياء',s5p:'مسارات عمل ذكية ومتصلة لأتمتة المهام المتكررة في الأعمال.',s6:'المقالات والكتب',s6p:'مقالات احترافية وكتب رقمية وقصص تفاعلية وتصميم تحريري.'});
Object.assign(copy.en,{searchPlaceholder:'Search services, architecture, AI, video, automation…',noResults:'No matching results found',searchType:'Open service'});
Object.assign(copy.fa,{searchPlaceholder:'جست‌وجوی خدمات، معماری، هوش مصنوعی، ویدئو، اتوماسیون…',noResults:'نتیجه‌ای پیدا نشد',searchType:'مشاهده خدمت'});
Object.assign(copy.ar,{searchPlaceholder:'ابحث عن الخدمات والعمارة والذكاء الاصطناعي والفيديو والأتمتة…',noResults:'لم يتم العثور على نتائج',searchType:'عرض الخدمة'});
Object.assign(copy.en,{freeToolsTitle:'Useful tools. Right in your browser.',freeToolsIntro:'Fast, practical tools for documents, images, design and everyday creative work.',ft1:'PDF Toolkit',ft1p:'Merge, split, organize and create PDFs locally.',ft2:'Image Toolkit',ft2p:'Resize, crop, compress and convert images.',ft3:'QR Code Studio',ft3p:'Create scannable QR codes for links and contact details.',ft4:'Social Media Size Maker',ft4p:'Crop and export images in exact social sizes.',ft5:'Color Palette Studio',ft5p:'Extract and export the dominant colors of any image.',ft6:'Architecture Unit & Scale Converter',ft6p:'Convert units, areas, volumes and drawing scales.',openTool:'Open Tool →',exploreTools:'Explore All Tools →'});
Object.assign(copy.fa,{freeToolsTitle:'ابزارهای کاربردی، مستقیم در مرورگر شما.',freeToolsIntro:'ابزارهای سریع و کاربردی برای اسناد، تصاویر، طراحی و کارهای خلاقانه روزمره.',ft1:'ابزار PDF',ft1p:'ساخت، ادغام، جداسازی و مرتب‌سازی PDF به‌صورت محلی.',ft2:'ابزار تصویر',ft2p:'تغییر اندازه، برش، فشرده‌سازی و تبدیل تصاویر.',ft3:'استودیوی QR Code',ft3p:'ساخت QR قابل اسکن برای لینک‌ها و اطلاعات تماس.',ft4:'سازنده ابعاد شبکه‌های اجتماعی',ft4p:'برش و خروجی تصویر با اندازه دقیق شبکه‌های اجتماعی.',ft5:'استودیوی پالت رنگ',ft5p:'استخراج و دانلود رنگ‌های اصلی هر تصویر.',ft6:'مبدل واحد و مقیاس معماری',ft6p:'تبدیل واحد، مساحت، حجم و مقیاس نقشه.',openTool:'بازکردن ابزار ←',exploreTools:'مشاهده همه ابزارها ←'});
Object.assign(copy.ar,{freeToolsTitle:'أدوات مفيدة، مباشرة في متصفحك.',freeToolsIntro:'أدوات سريعة وعملية للمستندات والصور والتصميم والعمل الإبداعي اليومي.',ft1:'أدوات PDF',ft1p:'إنشاء ودمج وتقسيم وترتيب ملفات PDF محلياً.',ft2:'أدوات الصور',ft2p:'تغيير الحجم والقص والضغط وتحويل الصور.',ft3:'استوديو رمز QR',ft3p:'أنشئ رموز QR قابلة للمسح للروابط وبيانات الاتصال.',ft4:'صانع مقاسات التواصل الاجتماعي',ft4p:'قص وتصدير الصور بالمقاسات الصحيحة.',ft5:'استوديو لوحة الألوان',ft5p:'استخرج وحمّل الألوان الأساسية من أي صورة.',ft6:'محول الوحدات والمقاييس المعمارية',ft6p:'تحويل الوحدات والمساحات والأحجام ومقاييس الرسم.',openTool:'افتح الأداة ←',exploreTools:'استكشف كل الأدوات ←'});
Object.assign(copy.en,{connectedTitle:'One studio. Everything connected.',connectedIntro:'A clear foundation for communication, commerce and quality-controlled publishing.',portfolioLink:'Portfolio',aboutLink:'About Us',contactLink:'Contact Us',faqLink:'FAQ',channelsLabel:'COMMUNICATION',channelsTitle:'Meet us everywhere.',readyConnect:'Ready to connect',channelsNote:'The icons are prepared. Final links can be connected when the official addresses are supplied.',commerceLabel:'PAYMENTS & COMMERCE',commerceTitle:'Built for international business.',foundationReady:'Foundation ready',paypalText:'International checkout connection',cryptoTitle:'Crypto wallet',cryptoText:'Direct wallet payment',bankText:'Through compatible payment gateways',adsText:'Ad placement infrastructure',invoice:'Invoice',cart:'Shopping Cart',customer:'Customer Account',automationLabel:'WEBSITE CONTENT AUTOMATION',automationTitle:'Research → Create → Review → Approve → Publish',automationText:'Automation for this website’s content—not sales automation. A professional daily publishing workflow with mandatory quality control.',centralBrain:'Website content orchestrator',creationBrain:'Drafting & reasoning',researchSources:'Source research',contentStorage:'Content storage',knowledgeBase:'Knowledge base',codeVersions:'Code, apps & versions',humanApproval:'Human approval',beforePublish:'Required before publishing',collectSources:'Collect your sources',prepareArticle:'Prepare professional article',qualityCheck:'Quality check',approvePublish:'Approve & publish on the website',activationNote:'Connection-ready design. Live website automation starts only after the required accounts, permissions and API credentials are securely connected.',aboutLabel:'ABOUT',aboutText:'Architecture, artificial intelligence and digital creativity shaped as one connected studio.',faqLabel:'FAQ',faqQuestion:'Are the integrations active now?',faqAnswer:'The structure is prepared. Each service becomes active after its official account and secure credentials are connected.'});
Object.assign(copy.fa,{connectedTitle:'یک استودیو؛ همه‌چیز متصل.',connectedIntro:'زیرساختی منظم برای ارتباطات، فروش و انتشار کنترل‌شده و حرفه‌ای.',portfolioLink:'نمونه‌کارها',aboutLink:'درباره ما',contactLink:'تماس با ما',faqLink:'سؤالات متداول',channelsLabel:'راه‌های ارتباطی',channelsTitle:'همه‌جا با ما در ارتباط باشید.',readyConnect:'آماده اتصال',channelsNote:'آیکون‌ها آماده‌اند و پس از دریافت آدرس‌های رسمی، لینک نهایی آن‌ها متصل می‌شود.',commerceLabel:'پرداخت و فروش',commerceTitle:'آماده برای کسب‌وکار بین‌المللی.',foundationReady:'زیرساخت آماده',paypalText:'اتصال پرداخت بین‌المللی',cryptoTitle:'کیف پول رمزارزی',cryptoText:'پرداخت مستقیم به کیف پول',bankText:'از مسیر درگاه‌های پرداخت سازگار',adsText:'زیرساخت جایگاه‌های تبلیغاتی',invoice:'فاکتور',cart:'سبد خرید',customer:'حساب مشتری',automationLabel:'اتوماسیون محتوای خود سایت',automationTitle:'تحقیق ← تولید ← بررسی ← تأیید ← انتشار',automationText:'این اتوماسیون برای محتوای خود سایت است، نه فروش؛ گردش‌کار حرفه‌ای روزانه با کنترل کیفیت اجباری.',centralBrain:'هماهنگ‌کننده محتوای سایت',creationBrain:'تولید و استدلال',researchSources:'تحقیق روی منابع',contentStorage:'نگهداری محتوا',knowledgeBase:'پایگاه دانش',codeVersions:'کد، اپلیکیشن و نسخه‌ها',humanApproval:'تأیید انسانی',beforePublish:'الزامی پیش از انتشار',collectSources:'دریافت منابع شما',prepareArticle:'آماده‌سازی مقاله حرفه‌ای',qualityCheck:'کنترل کیفیت',approvePublish:'تأیید و انتشار روی سایت',activationNote:'طراحی آماده اتصال است. اتوماسیون واقعی سایت فقط پس از اتصال امن حساب‌ها، مجوزها و کلیدهای لازم فعال می‌شود.',aboutLabel:'درباره ما',aboutText:'معماری، هوش مصنوعی و خلاقیت دیجیتال در قالب یک استودیوی یکپارچه.',faqLabel:'سؤالات متداول',faqQuestion:'آیا اتصال‌ها همین حالا فعال هستند؟',faqAnswer:'زیرساخت آماده شده است؛ هر سرویس پس از اتصال حساب رسمی و اطلاعات امن آن فعال می‌شود.'});
Object.assign(copy.ar,{connectedTitle:'استوديو واحد؛ كل شيء متصل.',connectedIntro:'بنية واضحة للتواصل والتجارة والنشر الاحترافي الخاضع للمراجعة.',portfolioLink:'الأعمال',aboutLink:'من نحن',contactLink:'اتصل بنا',faqLink:'الأسئلة الشائعة',channelsLabel:'التواصل',channelsTitle:'تواصل معنا في كل مكان.',readyConnect:'جاهز للربط',channelsNote:'الأيقونات جاهزة، وسيتم ربط العناوين النهائية عند توفير الحسابات الرسمية.',commerceLabel:'الدفع والتجارة',commerceTitle:'جاهز للأعمال الدولية.',foundationReady:'البنية جاهزة',paypalText:'ربط الدفع الدولي',cryptoTitle:'محفظة العملات الرقمية',cryptoText:'دفع مباشر إلى المحفظة',bankText:'عبر بوابات دفع متوافقة',adsText:'بنية مواضع الإعلانات',invoice:'الفاتورة',cart:'سلة التسوق',customer:'حساب العميل',automationLabel:'أتمتة محتوى الموقع',automationTitle:'بحث ← إنشاء ← مراجعة ← موافقة ← نشر',automationText:'هذه الأتمتة لمحتوى الموقع نفسه وليست للمبيعات؛ سير نشر يومي احترافي مع مراجعة جودة إلزامية.',centralBrain:'منسق محتوى الموقع',creationBrain:'الإنشاء والاستدلال',researchSources:'بحث المصادر',contentStorage:'حفظ المحتوى',knowledgeBase:'قاعدة المعرفة',codeVersions:'الكود والتطبيقات والإصدارات',humanApproval:'موافقة بشرية',beforePublish:'مطلوبة قبل النشر',collectSources:'جمع مصادرك',prepareArticle:'إعداد مقال احترافي',qualityCheck:'مراجعة الجودة',approvePublish:'الموافقة والنشر على الموقع',activationNote:'التصميم جاهز للربط. تبدأ أتمتة الموقع الفعلية فقط بعد ربط الحسابات والصلاحيات ومفاتيح الوصول المطلوبة بأمان.',aboutLabel:'من نحن',aboutText:'العمارة والذكاء الاصطناعي والإبداع الرقمي في استوديو واحد مترابط.',faqLabel:'الأسئلة الشائعة',faqQuestion:'هل التكاملات مفعلة الآن؟',faqAnswer:'تم تجهيز البنية، ويصبح كل اتصال فعالاً بعد ربط حسابه الرسمي وبياناته الآمنة.'});
Object.assign(copy.en,{installApp:'Install App'});Object.assign(copy.fa,{installApp:'نصب اپلیکیشن'});Object.assign(copy.ar,{installApp:'تثبيت التطبيق'});
Object.assign(copy.en,{navJournal:'Articles',articlesLabel:'ARTICLES',articlesTitle:'Expert articles',articlesText:'Research-led writing on architecture, artificial intelligence and digital creativity.',readJournal:'Explore articles →',dailyNewsLabel:'DAILY NEWS',dailyNewsTitle:'Today’s essential news',dailyNewsText:'A concise, reviewed selection of important developments across architecture, AI and technology.',readDailyNews:'View daily news →'});
Object.assign(copy.fa,{navJournal:'مقاله',articlesLabel:'مقاله‌ها',articlesTitle:'مقاله‌های تخصصی',articlesText:'مطالب پژوهش‌محور درباره معماری، هوش مصنوعی و خلاقیت دیجیتال.',readJournal:'مشاهده مقاله‌ها ←',dailyNewsLabel:'اخبار روز',dailyNewsTitle:'مهم‌ترین خبرهای امروز',dailyNewsText:'گزیده‌ای کوتاه و بررسی‌شده از تازه‌ترین رویدادهای معماری، هوش مصنوعی و فناوری.',readDailyNews:'مشاهده اخبار روز ←'});
Object.assign(copy.ar,{navJournal:'المقالات',articlesLabel:'المقالات',articlesTitle:'مقالات متخصصة',articlesText:'محتوى بحثي حول العمارة والذكاء الاصطناعي والإبداع الرقمي.',readJournal:'استكشف المقالات ←',dailyNewsLabel:'أخبار اليوم',dailyNewsTitle:'أهم أخبار اليوم',dailyNewsText:'مختارات موجزة ومدققة من أحدث تطورات العمارة والذكاء الاصطناعي والتقنية.',readDailyNews:'عرض أخبار اليوم ←'});
function syncEditorialCards(lang){
  const t=copy[lang]||copy.en;
  ['articlesLabel','articlesTitle','articlesText','readJournal','dailyNewsLabel','dailyNewsTitle','dailyNewsText','readDailyNews'].forEach(key=>{
    const el=document.querySelector(`[data-i18n="${key}"]`);
    if(el&&t[key])el.textContent=t[key];
  });
}
$$('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>syncEditorialCards(btn.dataset.lang)));
syncEditorialCards(localStorage.getItem('fd-language')||'en');
$$('[data-lang]').forEach(b=>b.onclick=()=>{const lang=b.dataset.lang;document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';$$('[data-lang]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-i18n]').forEach(el=>{const v=copy[lang][el.dataset.i18n];if(v)el.textContent=v})});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.animate([{opacity:0,transform:'translateY(60px) scale(.98)'},{opacity:1,transform:'none'}],{duration:850,easing:'cubic-bezier(.2,.8,.2,1)',fill:'both'})}),{threshold:.12});$$('.depth-section').forEach(s=>io.observe(s));

const serviceLabels={
  en:{architecture:'Architecture',ai:'AI & Content Creation',motion:'Teasers & Motion',web:'Web & App Design',automation:'Automation & Agents',editorial:'Articles & Books'},
  fa:{architecture:'معماری',ai:'هوش مصنوعی و تولید محتوا',motion:'تیزر و موشن',web:'طراحی سایت و اپلیکیشن',automation:'اتوماسیون و ایجنت',editorial:'مقاله و کتاب'},
  ar:{architecture:'الهندسة المعمارية',ai:'الذكاء الاصطناعي وصناعة المحتوى',motion:'الإعلانات والموشن',web:'تصميم المواقع والتطبيقات',automation:'الأتمتة والوكلاء',editorial:'المقالات والكتب'}
};
function setVideoLabels(lang){$$('[data-service]').forEach(el=>el.textContent=serviceLabels[lang][el.dataset.service])}
$$('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>setVideoLabels(btn.dataset.lang)));
video.addEventListener('timeupdate',()=>{
  const t=video.currentTime;
  $$('[data-group]').forEach(el=>{
    const g=el.dataset.group;
    const show=(g==='middle'&&t>=9.25&&t<11.70)||(g==='upper'&&t>=11.70&&t<14.20)||(g==='lower'&&t>=14.20&&t<16.80);
    el.classList.toggle('visible',show);
  });
});
video.addEventListener('ended',()=>$$('[data-group]').forEach(el=>el.classList.remove('visible')));
video.addEventListener('play',()=>hero.classList.add('video-active'));
video.addEventListener('ended',()=>hero.classList.remove('video-active'));

const quickInput=$('#quickSearch'),quickResults=$('#quickSearchResults'),quickShell=$('.quick-search-shell'),quickClear=$('#quickSearchClear');
const quickItems=[
  {key:'s1',url:'service.html?service=architecture',terms:'architecture interior exterior design bim revit rendering معماری داخلی خارجی طراحی عمارة داخلي خارجي'},
  {key:'s2',url:'service.html?service=ai',terms:'ai artificial intelligence ai content design هوش مصنوعی تولید محتوا الذكاء الاصطناعي المحتوى'},
  {key:'s3',url:'service.html?service=motion',terms:'video teaser logo motion advertising film ویدئو تیزر لوگوموشن تبلیغات فيديو موشن'},
  {key:'s4',url:'service.html?service=web',terms:'web website wordpress app application design سایت اپلیکیشن موقع تطبيق'},
  {key:'s5',url:'service.html?service=automation',terms:'automation agent make composio workflow اتوماسیون ایجنت أتمتة وكلاء'},
  {key:'s6',url:'service.html?service=editorial',terms:'articles books journal pdf مقاله کتاب مقالات كتب'}
];
let activeLanguage='en';
function renderQuickSearch(){
  const q=quickInput.value.trim().toLocaleLowerCase();quickShell.classList.toggle('has-value',Boolean(q));quickResults.textContent='';
  if(!q){quickResults.classList.remove('open');quickInput.setAttribute('aria-expanded','false');return}
  const found=quickItems.filter(item=>(item.terms+' '+copy[activeLanguage][item.key]).toLocaleLowerCase().includes(q));
  if(!found.length){const empty=document.createElement('div');empty.className='quick-search-empty';empty.textContent=copy[activeLanguage].noResults;quickResults.append(empty)}
  found.forEach(item=>{const link=document.createElement('a');link.className='quick-search-result';link.href=item.url;link.setAttribute('role','option');const name=document.createElement('span');name.textContent=copy[activeLanguage][item.key];const type=document.createElement('small');type.textContent=copy[activeLanguage].searchType;link.append(name,type);quickResults.append(link)});
  quickResults.classList.add('open');quickInput.setAttribute('aria-expanded','true');
}
quickInput.addEventListener('input',renderQuickSearch);quickInput.addEventListener('focus',()=>{if(quickInput.value.trim())renderQuickSearch()});
quickClear.addEventListener('click',()=>{quickInput.value='';renderQuickSearch();quickInput.focus()});
quickInput.addEventListener('keydown',e=>{if(e.key==='Escape'){quickResults.classList.remove('open');quickInput.setAttribute('aria-expanded','false')}if(e.key==='Enter'){const first=quickResults.querySelector('a');if(first)location.href=first.href}});
document.addEventListener('click',e=>{if(!quickShell.contains(e.target)){quickResults.classList.remove('open');quickInput.setAttribute('aria-expanded','false')}});
$$('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>{activeLanguage=btn.dataset.lang;quickInput.placeholder=copy[activeLanguage].searchPlaceholder;renderQuickSearch()}));

if(matchMedia('(hover:hover) and (pointer:fine)').matches){$$('.glass-card').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--tilt-y',`${((e.clientX-r.left)/r.width-.5)*7}deg`);card.style.setProperty('--tilt-x',`${(.5-(e.clientY-r.top)/r.height)*7}deg`);card.classList.add('tilting')});card.addEventListener('pointerleave',()=>{card.classList.remove('tilting');card.style.removeProperty('--tilt-x');card.style.removeProperty('--tilt-y')})})}
$$('[data-connect="later"]').forEach(link=>link.addEventListener('click',e=>e.preventDefault()));
let installPrompt;const installButton=$('#installApp');window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;installButton.hidden=false});installButton.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.hidden=true});window.addEventListener('appinstalled',()=>{installButton.hidden=true});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));

const seoCopy={
  en:{title:'Fourth Dimension Studio | Architecture, AI & Digital Design',description:'Fourth Dimension Studio creates architecture, BIM, AI content, motion, websites, applications and intelligent automation for international clients.',locale:'en_US'},
  fa:{title:'استودیو بُعد چهارم | معماری، هوش مصنوعی و طراحی دیجیتال',description:'استودیو بُعد چهارم در زمینه معماری، BIM، تولید محتوای هوش مصنوعی، موشن، سایت، اپلیکیشن و اتوماسیون هوشمند فعالیت می‌کند.',locale:'fa_IR'},
  ar:{title:'استوديو البعد الرابع | العمارة والذكاء الاصطناعي والتصميم الرقمي',description:'استوديو دولي للعمارة وBIM وصناعة المحتوى بالذكاء الاصطناعي والموشن والمواقع والتطبيقات والأتمتة الذكية.',locale:'ar_AR'}
};
function applyLanguageSeo(lang){
  const seo=seoCopy[lang]||seoCopy.en;
  const base='https://fourth-dimension-studio.infinityfreeapp.com/';
  const canonical=lang==='en'?`${base}?lang=en`:`${base}?lang=${lang}`;
  document.title=seo.title;
  document.querySelector('meta[name="description"]').content=seo.description;
  document.querySelector('link[rel="canonical"]').href=canonical;
  document.querySelector('meta[property="og:title"]').content=seo.title;
  document.querySelector('meta[property="og:description"]').content=seo.description;
  document.querySelector('meta[property="og:url"]').content=canonical;
  let locale=document.querySelector('meta[property="og:locale"]');if(!locale){locale=document.createElement('meta');locale.setAttribute('property','og:locale');document.head.append(locale)}locale.content=seo.locale;
  document.querySelector('meta[name="twitter:title"]').content=seo.title;
  document.querySelector('meta[name="twitter:description"]').content=seo.description;
  const url=new URL(location.href);url.searchParams.set('lang',lang);history.replaceState({},'',url);
  localStorage.setItem('fd-language',lang);
}
$$('[data-lang]').forEach(button=>button.addEventListener('click',()=>applyLanguageSeo(button.dataset.lang)));
const initialLang=new URLSearchParams(location.search).get('lang')||localStorage.getItem('fd-language')||'en';
if(/^(en|fa|ar)$/.test(initialLang)){const initialButton=document.querySelector(`[data-lang="${initialLang}"]`);if(initialButton)initialButton.click();else applyLanguageSeo(initialLang)}
