const services={
 architecture:{n:'01',icon:'⌂',en:['Architecture & BIM','From concept to build-ready spatial systems, detailed with BIM precision and presented through cinematic visualization.',['Architectural concept & planning','Interior and exterior design','Revit modeling & BIM documentation','Photorealistic rendering & animation'],['Discovery & site analysis','Concept and design direction','Modeling, refinement and review','Final drawings and visual delivery']],fa:['معماری و BIM','از ایده تا یک فضای آماده اجرا؛ با دقت BIM و ارائه‌ای سینمایی.',['کانسپت و برنامه‌ریزی معماری','طراحی داخلی و خارجی','مدل‌سازی Revit و مدارک BIM','رندر و انیمیشن واقع‌گرایانه'],['شناخت پروژه و تحلیل سایت','کانسپت و مسیر طراحی','مدل‌سازی، اصلاح و بازبینی','تحویل نقشه‌ها و تصاویر نهایی']],ar:['العمارة وBIM','من الفكرة إلى نظام مكاني جاهز للتنفيذ بدقة BIM وعرض سينمائي.',['المفهوم والتخطيط المعماري','التصميم الداخلي والخارجي','نمذجة Revit ووثائق BIM','الإظهار الواقعي والتحريك'],['فهم المشروع وتحليل الموقع','المفهوم واتجاه التصميم','النمذجة والمراجعة','تسليم الرسومات والصور النهائية']]},
 ai:{n:'02',icon:'✦',en:['AI & Content Creation','Distinctive visual content and intelligent creative systems, developed with human direction and AI speed.',['AI visual campaigns','Architecture image enhancement','Branded content systems','Creative prompting & art direction'],['Define audience and goal','Build the visual language','Create and refine assets','Deliver an organized content system']],fa:['هوش مصنوعی و تولید محتوا','محتوای تصویری متفاوت و سیستم‌های خلاق هوشمند با هدایت انسانی و سرعت هوش مصنوعی.',['کمپین تصویری با AI','ارتقای تصاویر معماری','سیستم محتوایی برند','پرامپت‌نویسی و آرت‌دایرکشن'],['تعیین مخاطب و هدف','ساخت زبان بصری','تولید و اصلاح محتوا','تحویل سیستم منظم محتوا']],ar:['الذكاء الاصطناعي وصناعة المحتوى','محتوى بصري مميز وأنظمة إبداعية ذكية بتوجيه بشري وسرعة الذكاء الاصطناعي.',['حملات بصرية بالذكاء الاصطناعي','تحسين الصور المعمارية','أنظمة محتوى للعلامات','هندسة الأوامر والإخراج الفني'],['تحديد الجمهور والهدف','بناء اللغة البصرية','الإنتاج والتحسين','تسليم نظام محتوى منظم']]},
 motion:{n:'03',icon:'▶',en:['Teasers & Motion','Cinematic films, logo motion and advertising built to hold attention and move audiences.',['Brand and product teasers','Logo motion & identity animation','Social advertising videos','Cinematic editing & sound design'],['Creative brief and script','Storyboard and visual direction','Production and motion design','Edit, sound and final formats']],fa:['تیزر و موشن','فیلم‌های سینمایی، لوگوموشن و تبلیغاتی که توجه مخاطب را حفظ می‌کنند.',['تیزر برند و محصول','لوگوموشن و هویت متحرک','ویدئوی تبلیغاتی شبکه‌های اجتماعی','تدوین سینمایی و طراحی صدا'],['بریف خلاق و سناریو','استوری‌بورد و مسیر بصری','تولید و طراحی موشن','تدوین، صدا و خروجی نهایی']],ar:['الإعلانات والموشن','أفلام سينمائية وتحريك شعارات وإعلانات تجذب الانتباه.',['إعلانات العلامات والمنتجات','تحريك الشعار والهوية','فيديوهات التواصل الاجتماعي','مونتاج سينمائي وتصميم صوتي'],['الملخص الإبداعي والسيناريو','لوحة القصة والاتجاه البصري','الإنتاج وتصميم الحركة','المونتاج والصوت والتسليم']]},
 web:{n:'04',icon:'◇',en:['Website & App Design','Immersive, multilingual digital experiences designed for clarity, interaction and conversion.',['3D and interactive websites','WordPress design & commerce','Mobile app experience design','Multilingual UX and responsive systems'],['Strategy and information structure','UX wireframes and visual design','Development and integration','Testing, launch and handover']],fa:['طراحی سایت و اپلیکیشن','تجربه‌های دیجیتال تعاملی و چندزبانه برای وضوح، تعامل و فروش بهتر.',['سایت سه‌بعدی و تعاملی','وردپرس و فروشگاه اینترنتی','طراحی تجربه اپلیکیشن موبایل','تجربه کاربری چندزبانه و واکنش‌گرا'],['استراتژی و ساختار اطلاعات','وایرفریم و طراحی بصری','توسعه و اتصال سرویس‌ها','آزمایش، انتشار و تحویل']],ar:['تصميم المواقع والتطبيقات','تجارب رقمية غامرة ومتعددة اللغات مصممة للتفاعل والتحويل.',['مواقع ثلاثية الأبعاد وتفاعلية','WordPress والتجارة الإلكترونية','تصميم تجربة تطبيقات الهاتف','تجربة متعددة اللغات ومتجاوبة'],['الاستراتيجية وهيكل المعلومات','تجربة المستخدم والتصميم البصري','التطوير والتكامل','الاختبار والإطلاق والتسليم']]},
 automation:{n:'05',icon:'⌁',en:['Automation & AI Agents','Connected workflows and AI agents that reduce repetitive work and keep your business moving.',['Make & Composio workflows','AI content and support agents','Google Drive and GitHub connections','Publishing and reporting automation'],['Map the current workflow','Design triggers and decisions','Connect tools and build agents','Test, monitor and document']],fa:['اتوماسیون و ایجنت‌های هوشمند','گردش‌کارها و ایجنت‌هایی که کارهای تکراری را کم می‌کنند و کسب‌وکار را جلو می‌برند.',['گردش‌کارهای Make و Composio','ایجنت محتوا و پشتیبانی','اتصال Google Drive و GitHub','اتوماسیون انتشار و گزارش'],['ترسیم روند فعلی','طراحی محرک‌ها و تصمیم‌ها','اتصال ابزارها و ساخت ایجنت','آزمایش، پایش و مستندسازی']],ar:['الأتمتة والوكلاء الأذكياء','مسارات مترابطة ووكلاء أذكياء تقلل العمل المتكرر وتدفع الأعمال للأمام.',['مسارات Make وComposio','وكلاء المحتوى والدعم','ربط Google Drive وGitHub','أتمتة النشر والتقارير'],['رسم سير العمل الحالي','تصميم المحفزات والقرارات','ربط الأدوات وبناء الوكلاء','الاختبار والمراقبة والتوثيق']]},
 editorial:{n:'06',icon:'▤',en:['Articles & Books','Expert knowledge shaped into credible articles, digital books and interactive reading experiences.',['Research-based expert articles','Digital and interactive books','Children’s story experiences','Editorial identity and layout'],['Source and audience definition','Research and narrative structure','Writing, editing and design','Review, publishing and delivery']],fa:['مقاله و کتاب','دانش تخصصی در قالب مقاله معتبر، کتاب دیجیتال و تجربه مطالعه تعاملی.',['مقاله تخصصی مبتنی بر تحقیق','کتاب دیجیتال و تعاملی','داستان تعاملی کودک','هویت بصری و صفحه‌آرایی'],['تعیین منابع و مخاطب','تحقیق و ساختار روایت','نگارش، ویرایش و طراحی','بازبینی، انتشار و تحویل']],ar:['المقالات والكتب','معرفة متخصصة في مقالات موثوقة وكتب رقمية وتجارب قراءة تفاعلية.',['مقالات متخصصة مبنية على البحث','كتب رقمية وتفاعلية','قصص أطفال تفاعلية','هوية تحريرية وتصميم الصفحات'],['تحديد المصادر والجمهور','البحث وبناء السرد','الكتابة والتحرير والتصميم','المراجعة والنشر والتسليم']]}
};
const ui={en:{back:'← All services',start:'Start a project',offer:'WHAT WE DELIVER',deliverables:'Deliverables',method:'HOW IT WORKS',process:'Process',closing:'Every project is shaped around your goals, audience and visual identity.',discuss:'Discuss your project →'},fa:{back:'همه خدمات →',start:'شروع پروژه',offer:'خروجی‌های پروژه',deliverables:'آنچه تحویل می‌گیرید',method:'روند همکاری',process:'مراحل انجام پروژه',closing:'هر پروژه متناسب با هدف، مخاطب و هویت بصری شما طراحی می‌شود.',discuss:'درباره پروژه صحبت کنیم ←'},ar:{back:'كل الخدمات →',start:'ابدأ مشروعاً',offer:'مخرجات المشروع',deliverables:'ما ستحصل عليه',method:'طريقة العمل',process:'مراحل المشروع',closing:'يتم تشكيل كل مشروع وفق أهدافك وجمهورك وهويتك البصرية.',discuss:'ناقش مشروعك ←'}};
Object.assign(ui.en,{areas:'SERVICE AREAS',capabilities:'What we do in this field',capabilitiesIntro:'Choose the exact service you need. Each path is tailored to your project.',viewArea:'Start this service →'});
Object.assign(ui.fa,{areas:'حوزه‌های این خدمت',capabilities:'در این بخش چه کارهایی انجام می‌دهیم؟',capabilitiesIntro:'خدمت دقیق موردنیازتان را انتخاب کنید؛ هر مسیر متناسب با پروژه شما اجرا می‌شود.',viewArea:'شروع این خدمت ←'});
Object.assign(ui.ar,{areas:'مجالات الخدمة',capabilities:'ماذا نقدم في هذا المجال؟',capabilitiesIntro:'اختر الخدمة الدقيقة التي تحتاجها؛ كل مسار يُصمم بما يناسب مشروعك.',viewArea:'ابدأ هذه الخدمة ←'});
const key=new URLSearchParams(location.search).get('service');const item=services[key]||services.architecture;
function renderSpecialties(lang,d){
  specialties.textContent='';
  d[2].forEach((title,index)=>{
    const card=document.createElement('article');card.className='specialty-card';
    const number=document.createElement('span');number.textContent=String(index+1).padStart(2,'0');
    const heading=document.createElement('h3');heading.textContent=title;
    const text=document.createElement('p');text.textContent=d[1];
    const link=document.createElement('a');link.textContent=ui[lang].viewArea;link.href='mailto:hello@fourthdimension.studio?subject='+encodeURIComponent(d[0]+' — '+title);
    card.append(number,heading,text,link);specialties.append(card);
  });
}
function setMeta(selector,attribute,value){let node=document.querySelector(selector);if(!node){node=document.createElement(attribute==='content'?'meta':'link');document.head.append(node)}node.setAttribute(attribute,value)}
function render(lang){document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.querySelectorAll('[data-ui]').forEach(el=>el.textContent=ui[lang][el.dataset.ui]);const d=item[lang];const canonical=`https://fourth-dimension-studio.infinityfreeapp.com/service.html?service=${encodeURIComponent(key||'architecture')}&lang=${lang}`;document.title=d[0]+' | Fourth Dimension Studio';setMeta('meta[name="description"]','content',d[1]);setMeta('link[rel="canonical"]','href',canonical);setMeta('meta[property="og:title"]','content',document.title);setMeta('meta[property="og:description"]','content',d[1]);setMeta('meta[property="og:url"]','content',canonical);serviceBreadcrumb.textContent=JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Fourth Dimension Studio',item:'https://fourth-dimension-studio.infinityfreeapp.com/'},{'@type':'ListItem',position:2,name:d[0],item:canonical}]});serviceIndex.textContent=item.n+' / SERVICE';serviceIcon.textContent=item.icon;serviceTitle.textContent=d[0];serviceIntro.textContent=d[1];deliverables.innerHTML=d[2].map(x=>'<li>'+x+'</li>').join('');process.innerHTML=d[3].map(x=>'<li>'+x+'</li>').join('');serviceCta.href='mailto:hello@fourthdimension.studio?subject='+encodeURIComponent(d[0]);renderSpecialties(lang,d);const url=new URL(location.href);url.searchParams.set('service',key||'architecture');url.searchParams.set('lang',lang);history.replaceState({},'',url)}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>render(b.dataset.lang));const requestedLang=new URLSearchParams(location.search).get('lang');render(/^(en|fa|ar)$/.test(requestedLang)?requestedLang:'en');
